import { Inter } from "next/font/google";
import "./globals.css";
import clsk from "clsx";
import { FirePointBackground } from "@/Components/FirePointBackground";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons:{
    icon:["/icon.png"],

  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsk(inter.variable, "bg-background text-foreground font-inter")}>
        {children}
        <FirePointBackground/>
      </body>
    </html>
  );
}
