/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PiyalakNuchim (https://sketchfab.com/PiyalakNuchim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eggplant-lamp-6232bcdabda9414d963f54e2456a465c
Title: Eggplant Lamp
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Lamp(props) {
  const { nodes, materials } = useGLTF('/models/lamp-transformed.glb')

  const modelRef=useRef()

  useFrame(()=>{
    modelRef.current.rotation.y +=0.007
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    scale={[8,8,8]}
    

    
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base_green_paint_0.geometry}
        material={materials.green_paint}
        rotation={[-Math.PI / 2, 0, -0.587]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bulb2_Lamp_0.geometry}
        material={materials.Lamp}
        position={[-0.034, 0.215, 0.056]}
        rotation={[-Math.PI / 2, 0, -0.587]}
        scale={2.132}
      />
    </group>
  )
}

useGLTF.preload('/models/lamp-transformed.glb')